random_state: 101
verbose: True
dataset:
  training_data_path: '/appDisease/predictor/dataset/training_data.csv'
  test_data_path: '/appDisease/predictor/dataset/test_data.csv'
  validation_size: 0.33
